# Generated by Django 6.1 on 2026-08-19 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_rename_courses_cou_categor_fec4a4_idx_courses_cou_categor_108713_idx_and_more'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='enrollments.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='courses.lesson')),
            ],
            options={
                'ordering': ['lesson__order'],
                'indexes': [models.Index(fields=['learner', 'completed'], name='progress_le_learner_f79d7d_idx'), models.Index(fields=['enrollment', 'completed'], name='progress_le_enrollm_c9fdd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'lesson'), name='unique_learner_lesson_progress')],
            },
        ),
    ]
