# Generated by Django 6.1 on 2026-08-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Article'), ('DOCUMENT', 'Document'), ('EXTERNAL', 'External Resource')], default='VIDEO', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('article_content', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='courses/documents/')),
                ('external_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursesection')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['section', 'order'], name='courses_les_section_573283_idx'), models.Index(fields=['content_type'], name='courses_les_content_d3cec9_idx'), models.Index(fields=['is_published'], name='courses_les_is_publ_ebf633_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'order'), name='unique_lesson_order_per_section')],
            },
        ),
    ]
