# Generated by Django 6.1 on 2026-08-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_cou_categor_108713_idx',
            old_name='courses_cou_categor_fec4a4_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='categories.category'),
        ),
    ]
